name: unit test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build_sphinx_doc_deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: conda init
        run: conda init bash
      - name: conda install
        run: |
          conda env create -f environment.yml
          conda activate calculator
      - name: unit test
        run: |
          conda list
          python -m unittest
