name: unit test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build_sphinx_doc_deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: calculator
          environment-file: environment.yml
          auto-activate-base: false
      - name: unit test
        run: |
          python -m unittest
