name: unit test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build_sphinx_doc_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: conda install
        run: conda env create -f environment.yml
      - name: unit test
        run: |
          conda list
          python -m unittest
